import os
import sqlite3
from contextlib import contextmanager
from pathlib import Path


CAMINHO_BANCO = Path(__file__).resolve().parent / "pcm.db"
DATABASE_URL = os.getenv("DATABASE_URL")
USAR_POSTGRES = bool(DATABASE_URL)


if USAR_POSTGRES:
    import psycopg
    from psycopg.rows import dict_row


def conectar_banco():
    """Abre o banco configurado para o ambiente atual."""
    if USAR_POSTGRES:
        return psycopg.connect(
            DATABASE_URL,
            row_factory=dict_row,
        )

    conexao = sqlite3.connect(CAMINHO_BANCO)
    conexao.row_factory = sqlite3.Row
    conexao.execute("PRAGMA foreign_keys = ON")
    return conexao


@contextmanager
def abrir_banco():
    conexao = conectar_banco()

    try:
        yield conexao
        conexao.commit()
    except Exception:
        conexao.rollback()
        raise
    finally:
        conexao.close()


def criar_tabelas():
    with abrir_banco() as conexao:
        if USAR_POSTGRES:
            conexao.execute(
                """
                CREATE TABLE IF NOT EXISTS produtos (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    nome TEXT NOT NULL,
                    categoria TEXT NOT NULL,
                    sku TEXT NOT NULL,
                    possui_variacao BOOLEAN NOT NULL DEFAULT FALSE,
                    preco_custo NUMERIC(12, 2) NOT NULL,
                    preco_venda NUMERIC(12, 2) NOT NULL,
                    lucro NUMERIC(12, 2) NOT NULL,
                    estoque INTEGER NOT NULL DEFAULT 0
                )
                """
            )

            conexao.execute(
                """
                CREATE TABLE IF NOT EXISTS variacoes (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    produto_id INTEGER NOT NULL,
                    nome TEXT NOT NULL,
                    estoque INTEGER NOT NULL DEFAULT 0,

                    FOREIGN KEY (produto_id)
                    REFERENCES produtos (id)
                    ON DELETE CASCADE
                )
                """
            )
            return

        conexao.execute(
            """
            CREATE TABLE IF NOT EXISTS produtos (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                nome TEXT NOT NULL,
                categoria TEXT NOT NULL,
                sku TEXT NOT NULL,
                possui_variacao INTEGER NOT NULL DEFAULT 0,
                preco_custo REAL NOT NULL,
                preco_venda REAL NOT NULL,
                lucro REAL NOT NULL,
                estoque INTEGER NOT NULL DEFAULT 0
            )
            """
        )

        conexao.execute(
            """
            CREATE TABLE IF NOT EXISTS variacoes (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                produto_id INTEGER NOT NULL,
                nome TEXT NOT NULL,
                estoque INTEGER NOT NULL DEFAULT 0,

                FOREIGN KEY (produto_id)
                REFERENCES produtos (id)
                ON DELETE CASCADE
            )
            """
        )


def _parametro():
    return "%s" if USAR_POSTGRES else "?"


def _montar_produto(conexao, linha_produto):
    if linha_produto is None:
        return None

    parametro = _parametro()
    linhas_variacoes = conexao.execute(
        f"""
        SELECT nome, estoque
        FROM variacoes
        WHERE produto_id = {parametro}
        ORDER BY id
        """,
        (linha_produto["id"],),
    ).fetchall()

    produto = dict(linha_produto)
    produto["possui_variacao"] = bool(produto["possui_variacao"])
    produto["variacoes"] = [linha["nome"] for linha in linhas_variacoes]
    produto["estoques_variacoes"] = {
        linha["nome"]: linha["estoque"]
        for linha in linhas_variacoes
    }

    return produto


def listar_produtos():
    with abrir_banco() as conexao:
        linhas = conexao.execute(
            "SELECT * FROM produtos ORDER BY id"
        ).fetchall()

        return [
            _montar_produto(conexao, linha)
            for linha in linhas
        ]


def buscar_produto(produto_id):
    parametro = _parametro()

    with abrir_banco() as conexao:
        linha = conexao.execute(
            f"SELECT * FROM produtos WHERE id = {parametro}",
            (produto_id,),
        ).fetchone()

        return _montar_produto(conexao, linha)


def _inserir_variacoes(conexao, produto_id, produto):
    parametro = _parametro()
    estoques = produto.get("estoques_variacoes", {})

    for variacao in produto.get("variacoes", []):
        conexao.execute(
            f"""
            INSERT INTO variacoes (produto_id, nome, estoque)
            VALUES ({parametro}, {parametro}, {parametro})
            """,
            (
                produto_id,
                variacao,
                estoques.get(variacao, 0),
            ),
        )


def inserir_produto(produto):
    parametro = _parametro()

    with abrir_banco() as conexao:
        if USAR_POSTGRES:
            cursor = conexao.execute(
                """
                INSERT INTO produtos (
                    nome, categoria, sku, possui_variacao,
                    preco_custo, preco_venda, lucro, estoque
                )
                VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
                RETURNING id
                """,
                (
                    produto["nome"],
                    produto["categoria"],
                    produto["sku"],
                    produto["possui_variacao"],
                    produto["preco_custo"],
                    produto["preco_venda"],
                    produto["lucro"],
                    produto["estoque"],
                ),
            )
            produto_id = cursor.fetchone()["id"]
        else:
            cursor = conexao.execute(
                """
                INSERT INTO produtos (
                    nome, categoria, sku, possui_variacao,
                    preco_custo, preco_venda, lucro, estoque
                )
                VALUES (?, ?, ?, ?, ?, ?, ?, ?)
                """,
                (
                    produto["nome"],
                    produto["categoria"],
                    produto["sku"],
                    int(produto["possui_variacao"]),
                    produto["preco_custo"],
                    produto["preco_venda"],
                    produto["lucro"],
                    produto["estoque"],
                ),
            )
            produto_id = cursor.lastrowid

        _inserir_variacoes(conexao, produto_id, produto)
        return produto_id


def atualizar_produto(produto_id, produto):
    parametro = _parametro()

    with abrir_banco() as conexao:
        if USAR_POSTGRES:
            resultado = conexao.execute(
                """
                UPDATE produtos
                SET nome = %s,
                    categoria = %s,
                    sku = %s,
                    possui_variacao = %s,
                    preco_custo = %s,
                    preco_venda = %s,
                    lucro = %s,
                    estoque = %s
                WHERE id = %s
                """,
                (
                    produto["nome"],
                    produto["categoria"],
                    produto["sku"],
                    produto["possui_variacao"],
                    produto["preco_custo"],
                    produto["preco_venda"],
                    produto["lucro"],
                    produto["estoque"],
                    produto_id,
                ),
            )
        else:
            resultado = conexao.execute(
                """
                UPDATE produtos
                SET nome = ?,
                    categoria = ?,
                    sku = ?,
                    possui_variacao = ?,
                    preco_custo = ?,
                    preco_venda = ?,
                    lucro = ?,
                    estoque = ?
                WHERE id = ?
                """,
                (
                    produto["nome"],
                    produto["categoria"],
                    produto["sku"],
                    int(produto["possui_variacao"]),
                    produto["preco_custo"],
                    produto["preco_venda"],
                    produto["lucro"],
                    produto["estoque"],
                    produto_id,
                ),
            )

        if resultado.rowcount == 0:
            return False

        conexao.execute(
            f"DELETE FROM variacoes WHERE produto_id = {parametro}",
            (produto_id,),
        )
        _inserir_variacoes(conexao, produto_id, produto)

        return True


def excluir_produto(produto_id):
    parametro = _parametro()

    with abrir_banco() as conexao:
        resultado = conexao.execute(
            f"DELETE FROM produtos WHERE id = {parametro}",
            (produto_id,),
        )

        return resultado.rowcount > 0


if __name__ == "__main__":
    criar_tabelas()
    banco = "PostgreSQL" if USAR_POSTGRES else "SQLite"
    print(f"Banco de dados criado com sucesso usando {banco}.")